import path from "node:path";
import { DEFAULT_CODEX_WATCH_INTERVAL_SECONDS, DEFAULT_CODEX_WATCH_ROTATE_BELOW_5H_REMAINING_PCT } from "../core/constants.js";

export function printHelp({ stdout = process.stdout } = {}) {
  const lines = [
    "aim — AI account manager (label-only; one-file SSOT; plaintext on disk).",
    "",
    "Usage:",
    "  aim status [--json] [--compact] [--accounts] [--assignments]",
    "  aim <label>            # primary human path: guided label panel on a TTY; one-shot login in non-interactive use",
    "  aim login <label>      # one-shot maintenance / automation / admin lane",
    "  aim login <label> --manual-callback-stdio  # scriptable manual OAuth: JSONL auth_url out, callback URL in",
    "  aim rebalance openclaw # choose pooled Codex assignments for configured OpenClaw agents",
    "  aim rebalance hermes   # choose pooled Codex assignments for live Hermes homes",
    "  aim apply             # advanced: materialize stored OpenClaw assignments from ~/.aimgr/secrets.json",
    "  aim sync openclaw     # explicit alias for apply",
    "  aim sync codex --from <authority>  # import/refresh openai-codex labels from an authority AIM state",
    "  aim promote codex --to <authority> <label> [<label>...]  # publish refreshed imported openai-codex labels back to the authority",
    "  aim sync claude --from <authority>  # import/refresh Claude labels from an authority AIM state",
    "  aim promote claude --to <authority> <label> [<label>...]  # publish refreshed imported Claude labels back to the authority",
    "  aim auth write hermes <label> --auth-file <abs-path>  # write Hermes auth.json only",
    "  aim codex use [label] # activate the next pooled openai-codex label, or explicitly switch a chosen label",
    "  aim codex watch [--once] [--interval-seconds <sec>] [--rotate-below-5h-remaining-pct <pct>]",
    "  aim codex run --tend [-p <profile>] [--resume <session-id>] [-- <codex args...>]  # run Codex TUI under tmux and tend stopped goals across account rotation",
    "  aim hermes watch [--once] [--interval-seconds <sec>] [--rotate-below-5h-remaining-pct <pct>]",
    "  aim claude use [label]  # activate the next-best pooled Claude label, or explicitly switch a chosen label",
    "  aim claude capture-native <label> [--source-home <dir>]",
    "  aim claude export-live --out <file> [--source-home <dir>]",
    "  aim claude import-native <label> --in <file>",
    "  aim pi use            # activate the next-best pooled openai-codex label for local Pi CLI",
    "  aim browser show <label>",
    "  aim browser set <label> --mode aim-profile [--seed-from-openclaw <profileId>]",
    "  aim browser set <label> --mode chrome-profile --user-data-dir <abs-path> [--profile-directory <name>]",
    "  aim browser set <label> --mode agent-browser --profile <abs-path> --session <name>",
    "  aim browser set <label> --mode manual-callback",
    "",
    "Notes:",
    "  - SSOT file: ~/.aimgr/secrets.json (auto-backed-up on every write).",
    "  - V0 supports: openai-codex (ChatGPT/Codex OAuth) + anthropic (Claude Pro/Max OAuth) on macOS.",
    "  - Browser-managed OAuth supports explicit per-label bindings: aim-profile, chrome-profile, or agent-browser.",
    "  - `aim pin`, `aim autopin openclaw`, and label-first `aim pi use` are removed; use `aim rebalance openclaw`, `aim apply`, `aim codex use [label]`, `aim claude use [label]`, and `aim pi use`.",
    "  - Codex target management is file-backed only in v1; keyring/auto homes fail loud.",
    `  - \`aim codex watch --once\` is the scheduler-safe one-shot; foreground watch loops default to ${DEFAULT_CODEX_WATCH_INTERVAL_SECONDS}s and rotate below ${DEFAULT_CODEX_WATCH_ROTATE_BELOW_5H_REMAINING_PCT}% 5h remaining.`,
    `  - \`aim hermes watch --once\` is the Hermes scheduler-safe one-shot and always delegates writes through \`aim rebalance hermes\`.`,
    "",
    "Developer options (rare):",
    "  --home <dir>    Run against an alternate HOME (dev/test; e.g. /tmp/aimgr-home).",
    "  --state <path>  Override SSOT file path (default: <home>/.aimgr/secrets.json).",
    "  --from <src>    Authority source for `aim sync codex` / `aim sync claude`.",
    "                  Examples: agents@amirs-mac-studio  |  ssh://agents@amirs-mac-studio/~/.aimgr/secrets.json",
    "  --to <dst>      Authority destination for `aim promote codex` / `aim promote claude`.",
    "                  Examples: agents@amirs-mac-studio  |  ssh://agents@amirs-mac-studio/~/.aimgr/secrets.json",
    "  --mode <id>     Browser binding mode for `aim browser set`.",
    "  --seed-from-openclaw <profileId>  Optional one-time OpenClaw seed source for `--mode aim-profile`.",
    "  --user-data-dir <abs-path>        Required for `--mode chrome-profile`.",
    "  --profile-directory <name>        Optional specific Chrome profile inside `--user-data-dir`.",
    "  --profile <abs-path>              Required for `--mode agent-browser`; accepted as Codex profile for `aim codex run --tend`.",
    "  --session <name>                  Required for `--mode agent-browser`.",
    "  --auth-file <abs-path>            Required for `aim auth write hermes`; must point at Hermes auth.json.",
    "  --codex-bin <path>                Optional Codex executable for `aim codex run --tend`.",
    "  -p, --codex-profile <name>        Optional Codex config profile for `aim codex run --tend`.",
    "  --resume, --session-id <id>       Resume and tend an existing Codex session UUID.",
    "  --tmux-session <name>             Optional tmux session name for `aim codex run --tend`.",
    "  --no-attach                      Start the tmux session without attaching the current terminal.",
    "  --max-restarts <n>                Maximum account-rotation resumes for `aim codex run --tend`.",
    "  --poll-seconds <sec>              Poll interval for `aim codex run --tend`.",
    "  --prompt-timeout-seconds <sec>    How long to wait for Codex's resume-goal prompt.",
    "  --workdir <dir>                   Working directory for the tended Codex tmux session.",
    "  --in <file>                       Required for `aim claude import-native`.",
    "  --out <file>                      Required for `aim claude export-live`.",
    "  --source-home <dir>               Optional source HOME for native Claude capture/export on the same host.",
    "  --discard-dirty                   Allow `aim sync codex` / `aim sync claude` to overwrite locally refreshed imported labels that were not promoted.",
    "  --manual-callback-stdio           Machine protocol for `aim login <label>`: emit auth_url JSONL, read callback URL from stdin.",
    "",
  ];
  stdout.write(`${lines.join("\n")}\n`);
}
