import {
  AIMGR_REDIS_DEFAULT_KEY_PREFIX,
  AIMGR_REDIS_PRIMARY_LOCAL_URL,
  AIMGR_REDIS_PRIMARY_HOST,
  AIMGR_REDIS_PRIMARY_URL,
  AIMGR_REDIS_TRANSPORT,
  DEFAULT_CODEX_WATCH_INTERVAL_SECONDS,
  DEFAULT_CODEX_WATCH_ROTATE_BELOW_5H_REMAINING_PCT,
} from "../core/constants.js";

export function printHelp({ stdout = process.stdout } = {}) {
  const lines = [
    "aim — AI account manager (Redis-backed shared credential state; local target files are projections).",
    "",
    "Usage:",
    "  aim status [--json] [--compact] [--accounts] [--assignments]",
    "  aim redis configure --url <redis-url> [--key-prefix <prefix>] [--primary-host <host>] [--transport tailscale]",
    "  aim redis config | ping | snapshot",
    "  aim redis export --out <file>",
    "  aim redis import --in <file>  # Claude records must be policy-only; credential/identity material is rejected",
    "  aim label rebind <label> --provider <provider> --confirm",
    "  aim <label>            # primary human path: guided label panel on a TTY; one-shot login in non-interactive use",
    "  aim login <label>      # one-shot maintenance / automation / admin lane",
    "  aim login <label> --manual-callback-stdio  # scriptable manual OAuth: JSONL auth_url out, callback URL in",
    "  aim rebalance openclaw # choose pooled Codex assignments for configured OpenClaw agents",
    "  aim rebalance hermes   # choose pooled Codex assignments for live Hermes homes",
    "  aim auth write hermes <label> --auth-file <abs-path>  # write Hermes auth.json only",
    "  aim auth maintain     # refresh due Redis-backed Claude and Codex OAuth credentials once",
    "  aim codex use [label] # activate the eligible openai-codex label with the lowest current 5h usage, or explicitly switch a chosen label",
    "  aim codex watch [--once] [--interval-seconds <sec>] [--rotate-below-5h-remaining-pct <pct>]",
    "  aim hermes watch [--once] [--interval-seconds <sec>] [--rotate-below-5h-remaining-pct <pct>]",
    "  aim claude list [count] [--json]  # show recent local managed Claude sessions (default: 50)",
    "  aim claude resume <row-or-thread-id-or-name> [--account <label>] [--switch-account fable|opus]  # optionally fork onto an exact label or the least-used unlocked account",
    "  aim claude run (opus|fable) [--resume]  # launch an unlocked account by preset usage: Fable-scoped for fable, shared 5h for opus",
    "  aim claude run <label> (opus|fable) [--resume]  # common one-line managed Claude launch presets",
    "  aim claude run <label> [-- <claude args...>]  # project the Redis-backed Claude label into a per-label home and launch Claude",
    "  aim claude inventory [--json]  # Redis-backed Claude account coverage; zero provider requests",
    "  aim claude status [account...] [--fresh] [--verbose] [--json]  # human account availability; --verbose shows technical state",
    "  aim claude usage [account...] [--fresh] [--verbose] [--json]   # exact alias for `aim claude status`",
    "  aim claude capture-native <label> [--source-home <dir>] [--source-config-dir <dir>]",
    "  aim claude export-live --out <file> [--source-home <dir>]",
    "  aim claude import-native <label> --in <file>",
    "  aim pi use            # activate the next-best pooled openai-codex label for local Pi CLI",
    "  aim sakana add <account-name> [--key <api-key>] [--tier standard|pro|max|payg] [--subscription <name>] [--notes <text>]",
    "  aim sakana use <account-name>  # write selected key to ~/.codex/.env as SAKANA_API_KEY",
    "  aim sakana list [--json] | aim sakana show <account-name> | aim sakana remove <account-name>",
    "  aim browser show <label>",
    "  aim browser set <label> --mode aim-profile [--seed-from-openclaw <profileId>]",
    "  aim browser set <label> --mode chrome-profile --user-data-dir <abs-path> [--profile-directory <name>]",
    "  aim browser set <label> --mode agent-browser --profile <abs-path> --session <name>",
    "  aim browser set <label> --mode manual-callback",
    "",
    "Notes:",
    `  - Shared SSOT: Redis at the configured Mac Studio primary, normally ${AIMGR_REDIS_PRIMARY_URL} for remote clients.`,
    `  - On ${AIMGR_REDIS_PRIMARY_HOST} itself, configure ${AIMGR_REDIS_PRIMARY_LOCAL_URL}; that host talks to its own container over localhost.`,
    "  - Local adjunct file: ~/.aimgr/local-state.json contains local-only target metadata; Redis is the Claude credential authority.",
    "  - Legacy ~/.aimgr/secrets.json is a backup artifact only; runtime commands ignore it.",
    "  - Managed Claude run/login requires an executable native Claude installation; managed macOS homes also require AIM's installed file-storage adapter.",
    "  - Browser-managed OAuth supports explicit per-label bindings: aim-profile, chrome-profile, or agent-browser.",
    "  - Generic Redis import never writes Claude credentials; use leased `aim claude capture-native` or `aim claude import-native`.",
    "  - Claude access-token refresh is published during managed runs and at exit; `aim login <label>` handles genuine reauthentication.",
    "  - Codex target management is file-backed only in v1; keyring/auto homes fail loud.",
    `  - \`aim codex watch --once\` is the scheduler-safe one-shot; foreground watch loops default to ${DEFAULT_CODEX_WATCH_INTERVAL_SECONDS}s and rotate below ${DEFAULT_CODEX_WATCH_ROTATE_BELOW_5H_REMAINING_PCT}% 5h remaining.`,
    `  - \`aim hermes watch --once\` is the Hermes scheduler-safe one-shot and always delegates writes through \`aim rebalance hermes\`.`,
    "",
    "Developer options (rare):",
    "  --home <dir>    Run against an alternate HOME (dev/test; e.g. /tmp/aimgr-home).",
    "  --url <redis-url>              Redis URL for `aim redis configure` or admin override.",
    `  --key-prefix <prefix>          Redis key prefix (default: ${AIMGR_REDIS_DEFAULT_KEY_PREFIX}).`,
    `  --primary-host <host>          Human-readable Redis primary host, e.g. ${AIMGR_REDIS_PRIMARY_HOST}.`,
    `  --transport <name>             Redis transport metadata, e.g. ${AIMGR_REDIS_TRANSPORT}.`,
    "  --provider <id>                Provider disambiguation for Redis repair commands.",
    "  --confirm                      Required for Redis label repair commands.",
    "  --mode <id>     Browser binding mode for `aim browser set`.",
    "  --seed-from-openclaw <profileId>  Optional one-time OpenClaw seed source for `--mode aim-profile`.",
    "  --user-data-dir <abs-path>        Required for `--mode chrome-profile`.",
    "  --profile-directory <name>        Optional specific Chrome profile inside `--user-data-dir`.",
    "  --profile <abs-path>              Required for `--mode agent-browser`.",
    "  --session <name>                  Required for `--mode agent-browser`.",
    "  --auth-file <abs-path>            Required for `aim auth write hermes`; must point at Hermes auth.json.",
    "  -- <claude args...>               For `aim claude run`, arguments after -- pass unchanged to Claude.",
    "  --in <file>                       Required for `aim redis import` or `aim claude import-native`; generic import accepts Claude policy only.",
    "  --out <file>                      Required for `aim claude export-live`.",
    "  --source-home <dir>               Optional source HOME for native Claude capture/export on the same host.",
    "  --source-config-dir <dir>         Exact isolated Claude config directory for Keychain-backed native capture.",
    "  --manual-callback-stdio           Machine protocol for `aim login <label>`: emit auth_url JSONL, read callback URL from stdin.",
    "",
  ];
  stdout.write(`${lines.join("\n")}\n`);
}
